server:
  port: 8080

spring:
  datasource:
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate

rental:
  near:
    distance: 100

stacktrace:
  app:
    packages: